In [4]:
import numpy as np

In [5]:
x = np.array(([2,9],[1,5],[3,6]),dtype=float)
y = np.array(([92],[86],[89]),dtype=float)
print(x)
print(y)

[[2. 9.]
 [1. 5.]
 [3. 6.]]
[[92.]
 [86.]
 [89.]]


In [6]:
x = x/np.amax(x,axis=0) 
y = y/100 

print(x)
print(y)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [15]:
class Neural_Network(object):
    def __init__(self):
        np.random.seed(0)
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        self.W1 = np.random.randn(self.inputSize,self.hiddenSize)
        print("w1",self.W1)
        self.W2 = np.random.randn(self.hiddenSize,self.outputSize)
        print("w1",self.W1)

    def forward(self,x):
        self.z1 = np.dot(x,self.W1)
        self.z2 = self.sigmoid(self.z1)
        self.z3 = np.dot(self.z2,self.W2)
        output = self.sigmoid(self.z3)
        return output
    
    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    
    def sigmoidPrime(self,s):
        return s*(1-s)
    
    def backward(self,x,y,output):
        self.output_error = y - output
        self.output_delta = self.output_error * self.sigmoidPrime(output)
        self.z2_error = self.output_delta.dot(self.W2.T)
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.z2)
        self.W1 += x.T.dot(self.z2_delta)
        self.W2 += self.z2.T.dot(self.output_delta)

    def train(self,x,y):
        Output = self.forward(x)
        self.backward(x,y,Output)

In [16]:
NN = Neural_Network()

w1 [[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]]
w1 [[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]]


In [6]:
for i in range(1000):
    print(f"Data in epoch {i}")
    print("Input : "+str(x))
    print("Actual Output : "+str(y))
    print("Predicted Output : "+str(NN.forward(x)))
    print("Loss : "+str(np.mean(np.square(y - NN.forward(x)))))
    print("\n")
    #Training The Model
    NN.train(x,y)

Data in epoch 0
Input : [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output : [[0.92]
 [0.86]
 [0.89]]
Predicted Output : [[0.67727117]
 [0.65870127]
 [0.67437581]]
Loss : 0.04864408481709518


Data in epoch 1
Input : [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output : [[0.92]
 [0.86]
 [0.89]]
Predicted Output : [[0.7332921 ]
 [0.71083177]
 [0.73144876]]
Loss : 0.027416499047308047


Data in epoch 2
Input : [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output : [[0.92]
 [0.86]
 [0.89]]
Predicted Output : [[0.76738691]
 [0.74320723]
 [0.76615786]]
Loss : 0.017422727887500933


Data in epoch 3
Input : [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output : [[0.92]
 [0.86]
 [0.89]]
Predicted Output : [[0.79027664]
 [0.76528833]
 [0.78944033]]
Loss : 0.011970232008063597


Data in epoch 4
Input : [[0.66666667 1.        ]
 [0.33333333 0.55555